FROM python:3.13-slim

WORKDIR /app

COPY . .

RUN pip install uv

RUN uv pip install \
fastapi \
uvicorn \
sqlalchemy \
psycopg[binary]

CMD [
 "uvicorn",
 "app.main:app",
 "--host",
 "0.0.0.0",
 "--port",
 "8000"
]