"""create lmp prices

Revision ID: 4cd49211d786
Revises: 
Create Date: 2026-06-24 18:04:54.290761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cd49211d786'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lmp_prices',
    sa.Column('ts', sa.TIMESTAMP(), nullable=False),
    sa.Column('node', sa.String(), nullable=False),
    sa.Column('market', sa.String(), nullable=False),
    sa.Column('lmp', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('ts', 'node', 'market')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lmp_prices')
    # ### end Alembic commands ###
